version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker images for microservices
          command: |
            curl -fsSl https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v

            TIMESTAMP=$(date +%s)
            DOCKER_TAG="v1_${TIMESTAMP}"

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed $DOCKER_REPO/udagram-api-feed:$DOCKER_TAG

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user $DOCKER_REPO/udagram-api-user:$DOCKER_TAG

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend $DOCKER_REPO/udagram-frontend:$DOCKER_TAG

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy $DOCKER_REPO/udagram-reverseproxy:$DOCKER_TAG

            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            docker push $DOCKER_REPO/udagram-api-feed:$DOCKER_TAG
            docker push $DOCKER_REPO/udagram-api-user:$DOCKER_TAG
            docker push $DOCKER_REPO/udagram-frontend:$DOCKER_TAG
            docker push $DOCKER_REPO/udagram-reverseproxy:$DOCKER_TAG

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
